services:
  php-apache:
    container_name: slim-flash-messages
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    restart: always
    volumes:
      - .:/var/www/html